version: "3"
services:
  # db:
  #   container_name: 'database-node'
  #   image: mysql:5.7.40
  #   volumes:
  #     - /src/database:/home/mysql
  #   # command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
  #   restart: always
  #   ports:
  #     - '3306:3306'
  #   environment:
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=true
  #     - TZ=America_Sao_Paulo

  node:
    build: ./app-api/
    image: victobernardo/automec_project:app-api
    command: "npm run start"
    working_dir: /home/node/app
    # environment:
    #   - NODE_ENV=production
      # - DB_HOST=db
    expose:
      - "3000"
    ports:
    - "3000:3000"
    networks:
      - net
    # links:
    #   - db
    # depends_on:
    #   - db
    
  auth:
    build: ./auth/
    image: victobernardo/automec_project:auth
    command: "npm run start"
    environment:
      - NODE_ENV=production
    expose:
      - "3030"
    ports:
      - "3030:3030"
    networks:
      - net

  react:
    build: ./app-front/
    image: victobernardo/automec_project:app-front
    command: "npm run start"
    stdin_open: true
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    networks:
      - net

  nginx:
    depends_on:
      - node
      - react
    restart: always
    build: ./nginx
    image: victobernardo/automec_project:nginx
    ports:
      - "3050:3050"
    networks:
      - net

networks:
  net:
    driver: 
      bridge