version: "3"
services:
  api:
    # build: ./app-api/
    image: victobernardo/automec_project:app-api
    command: "npm run start"
    working_dir: /home/node/app
    expose:
      - "3000"
    ports:
    - "3000:3000"
    networks:
      - net
    
  auth:
    # build: ./auth/
    image: victobernardo/automec_project:auth
    command: "npm run start"
    environment:
      - NODE_ENV=production
    expose:
      - "3030"
    ports:
      - "3030:3030"
    networks:
      - net

  react:
    # build: ./app-front/
    image: victobernardo/automec_project:app-front
    command: "npm run start"
    stdin_open: true
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    networks:
      - net

  nginx:
    depends_on:
      - api
      - react
    restart: always
    # build: ./nginx
    image: victobernardo/automec_project:nginx
    ports:
      - "3050:3050"
    networks:
      - net

networks:
  net:
    driver: 
      bridge