const { DataTypes } = require("sequelize");
module.exports = (sequelize) => {
    const attributes = {
        idCliente: {
            type: DataTypes.INTEGER(11),
            allowNull: false,
            defaultValue: null,
            primaryKey: true,
            autoIncrement: true,
            comment: null,
            field: "idCliente",
        },
        nomeCliente: {
            type: DataTypes.STRING(60),
            allowNull: true,
            defaultValue: null,
            primaryKey: false,
            autoIncrement: false,
            comment: null,
            field: "nomeCliente",
        },
        cpfCnpj: {
            type: DataTypes.STRING(18),
            allowNull: true,
            defaultValue: null,
            primaryKey: false,
            autoIncrement: false,
            comment: null,
            field: "cpfCnpj",
            unique: "cpfCnpj",
        },
        celularCliente: {
            type: DataTypes.STRING(20),
            allowNull: true,
            defaultValue: null,
            primaryKey: false,
            autoIncrement: false,
            comment: null,
            field: "celularCliente",
        },
        telefoneCliente: {
            type: DataTypes.STRING(20),
            allowNull: true,
            defaultValue: null,
            primaryKey: false,
            autoIncrement: false,
            comment: null,
            field: "telefoneCliente",
        },
        cep: {
            type: DataTypes.STRING(14),
            allowNull: true,
            defaultValue: null,
            primaryKey: false,
            autoIncrement: false,
            comment: null,
            field: "cep",
        },
        endereco: {
            type: DataTypes.STRING(60),
            allowNull: true,
            defaultValue: null,
            primaryKey: false,
            autoIncrement: false,
            comment: null,
            field: "endereco",
        },
        numero: {
            type: DataTypes.STRING(6),
            allowNull: true,
            defaultValue: null,
            primaryKey: false,
            autoIncrement: false,
            comment: null,
            field: "numero",
        },
        bairro: {
            type: DataTypes.STRING(60),
            allowNull: true,
            defaultValue: null,
            primaryKey: false,
            autoIncrement: false,
            comment: null,
            field: "bairro",
        },
        cidade: {
            type: DataTypes.STRING(60),
            allowNull: true,
            defaultValue: null,
            primaryKey: false,
            autoIncrement: false,
            comment: null,
            field: "cidade",
        },
        uf: {
            type: DataTypes.STRING(2),
            allowNull: true,
            defaultValue: null,
            primaryKey: false,
            autoIncrement: false,
            comment: null,
            field: "uf",
        },
        complemento: {
            type: DataTypes.STRING(60),
            allowNull: true,
            defaultValue: null,
            primaryKey: false,
            autoIncrement: false,
            comment: null,
            field: "complemento",
        },
    };
    const options = {
        tableName: "Cliente",
        comment: "",
        indexes: [],
    };
    const ClienteModel = sequelize.define("clienteModel", attributes, options);
    return ClienteModel;
};
